name: Node.js CI

on:
  push:
    branches: [master, cicd]
  pull_request:
    branches: [master, cicd]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: rm -rf node_modules && yarn install --frozen-lockfile
      - run: cd client && rm -rf node_modules && yarn install --frozen-lockfile && cd ..
      - run: cd server && rm -rf node_modules && yarn install --frozen-lockfile && cd ..
      - run: cd client && yarn build && cd ..
      - run: env PORT=3000 NODE_ENV=production node server/src/index.js
